In [1]:
import numpy as np

In [3]:
list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

In [5]:
array = np.array(list)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
array = np.arange(0,20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
array = np.arange(0,20,2)
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
array = np.linspace(0,20)
array

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [10]:
array = np.linspace(0,20,7)
array

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [13]:
array = np.zeros((3,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
array = np.ones((3,5),dtype=int)
array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
array = np.eye(4,5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [20]:
array = np.eye(4,5,dtype=int)
array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [22]:
# RESHAPE
array = np.reshape(np.array([0,1,2,3,4,5,6,7,8,9]),(2,5))
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
# RESHAPE
array = np.reshape(np.array([0,1,2,3,4,5,6,7,8,9]),(2,5))
array = np.ravel(array)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# RESHAPE
array = np.reshape(np.array([0,1,2,3,4,5,6,7,8,9]),(2,5))
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
# RESHAPE
array = np.transpose(array)
array

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [35]:
array1 = np.arange(0,10).reshape(2,5)
array2 = np.arange(10,25).reshape(3,5)
stacked = np.vstack([array1, array2])
stacked

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
array1 = np.arange(0,10).reshape(2,5)
array2 = np.arange(10,26).reshape(4,4)
stacked = np.vstack([array1, array2])
stacked

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [37]:
array1 = np.arange(0,10)
output = np.add(array1,5)
output

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
array1 = np.arange(0,10)
output = np.power(array1,5)
output

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049], dtype=int32)

In [41]:
array1 = np.arange(0,10)
output = np.sqrt(array1)
output

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
array1 = np.arange(0,10)
array2 = np.arange(10,20)
output = np.dot(array1,array2)
output

735

In [43]:
array1 = np.arange(0,10)
np.mean(array1)

4.5

In [44]:
array1 = np.arange(0,10)
np.median(array1)

4.5

In [45]:
array1 = np.arange(0,10)
np.max(array1)

9

In [46]:
array1 = np.arange(0,10)
np.min(array1)

0

In [47]:
array1 = np.arange(0,10)
np.std(array1)

2.8722813232690143

In [52]:
array1 = np.arange(20,29).reshape(3,3)
np.linalg.det(array1)

8.659739592076096e-15

In [53]:
array1 = np.arange(20,29).reshape(3,3)
np.linalg.inv(array1)

array([[-3.46430741e+14,  6.92861481e+14, -3.46430741e+14],
       [ 6.92861481e+14, -1.38572296e+15,  6.92861481e+14],
       [-3.46430741e+14,  6.92861481e+14, -3.46430741e+14]])

In [56]:
randomFloat = np.random.rand(3)
randomFloat

array([0.4586628 , 0.86580625, 0.98798209])

In [58]:
# Set seed for reproducibility
np.random.seed(0)
randomFloat = np.random.rand(3)
randomFloat

array([0.5488135 , 0.71518937, 0.60276338])

In [60]:
# Set seed for reproducibility
np.random.seed(0)
randomFloat = np.random.rand(3)
randomFloat

array([0.5488135 , 0.71518937, 0.60276338])

In [62]:
np.random.seed(0)
randomInt = np.random.rand(3,10)
randomInt

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
        0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
        0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]])

In [64]:
np.random.seed(0)
randomInt = np.random.rand(3,10)
randomInt

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
        0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
        0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]])

In [65]:
logical_test = np.array([True, True, True])
all_true = np.all(logical_test)
all_true

True

In [66]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
all_true

False

In [67]:
logical_test = np.array([True, True, True])
all_true = np.any(logical_test)
all_true

True

In [68]:
array1 = np.array([1,2,3,4])
array2 = np.array([3,4,5,6])
output = np.intersect1d(array1,array2)
output

array([3, 4])

In [69]:
array1 = np.array([1,2,3,4])
array2 = np.array([3,4,5,6])
output = np.union1d(array1,array2)
output

array([1, 2, 3, 4, 5, 6])

In [70]:
output = np.arange(0,20).reshape(4,5)
output

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
output = np.arange(0,20).reshape(4,5)
aShape = output.shape
aSize = output.size
aDimen = output.ndim
aData = output.dtype
size = output.nbytes

print(aShape,aSize,aDimen,aData,size)

(4, 5) 20 2 int32 80


In [76]:
output = np.arange(0,20).reshape(4,5)
copy_output = output.copy()
copy_output

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
output = np.arange(0,20).reshape(4,5)
copy_output = output.copy()
shared = np.shares_memory(output, copy_output)
shared

False

In [79]:
output = np.arange(0,20).reshape(4,5)
copy_output = output
shared = np.shares_memory(output, copy_output)
shared

True