In [8]:
import numpy as np

In [11]:
print("NUMPY RESHAPE FUNCTION")
np.arange(10,40,(3,3))

NUMPY RESHAPE FUNCTION


TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [12]:
np.arange(10,40).reshape(3,3)

ValueError: cannot reshape array of size 30 into shape (3,3)

In [14]:
np.random.randint(10,40).reshape(3,3)

AttributeError: 'int' object has no attribute 'reshape'

In [15]:
np.arange(10,40).reshape(5,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [16]:
np.arange(10,40).reshape(1,30)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [17]:
np.arange(10,40).reshape(30,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39]])

In [18]:
np.arange(10,40).reshape(10,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [21]:
matrix = np.random.randint(10,50,(5,6))
matrix

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26],
       [17, 32, 30, 26, 39, 29],
       [36, 15, 39, 20, 10, 26]])

In [23]:
matrix[1:3]

array([[41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26]])

In [24]:
matrix[1:3,1:3]

array([[34, 27],
       [43, 43]])

In [53]:
matrix[:,1:3]

array([[38, 12],
       [34, 27],
       [43, 43],
       [32, 30],
       [15, 39]])

In [54]:
matrix[1:3,:]

array([[41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26]])

In [55]:
matrix[::-1]

array([[36, 15, 39, 20, 10, 26],
       [17, 32, 30, 26, 39, 29],
       [34, 43, 43, 28, 44, 26],
       [41, 34, 27, 22, 13, 46],
       [41, 38, 12, 22, 31, 10]])

In [27]:
matrix

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26],
       [17, 32, 30, 26, 39, 29],
       [36, 15, 39, 20, 10, 26]])

In [31]:
matrix[1,2]

27

In [32]:
matrix[-3,-4]

43

In [33]:
matrix[1,-1]

46

In [34]:
matrix

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26],
       [17, 32, 30, 26, 39, 29],
       [36, 15, 39, 20, 10, 26]])

In [35]:
matrix[:]

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26],
       [17, 32, 30, 26, 39, 29],
       [36, 15, 39, 20, 10, 26]])

In [36]:
matrix[:-1]

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26],
       [17, 32, 30, 26, 39, 29]])

In [37]:
matrix[::-1]

array([[36, 15, 39, 20, 10, 26],
       [17, 32, 30, 26, 39, 29],
       [34, 43, 43, 28, 44, 26],
       [41, 34, 27, 22, 13, 46],
       [41, 38, 12, 22, 31, 10]])

In [39]:
matrix

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26],
       [17, 32, 30, 26, 39, 29],
       [36, 15, 39, 20, 10, 26]])

In [38]:
matrix[-1:]

array([[36, 15, 39, 20, 10, 26]])

In [40]:
matrix[0:-2]

array([[41, 38, 12, 22, 31, 10],
       [41, 34, 27, 22, 13, 46],
       [34, 43, 43, 28, 44, 26]])

In [42]:
matrix[-4,-2]

13

In [44]:
matrix2 = np.random.randint(0,100,(10,10))
matrix2

array([[55, 35,  1, 82, 46, 62, 38, 81, 76,  2],
       [ 1, 31, 98, 85, 48, 39, 41, 24,  5, 74],
       [83, 56, 22, 77, 83,  4, 33, 82, 91, 71],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14],
       [42, 53, 82,  3, 73, 47, 50, 83, 11, 94],
       [89, 84, 96, 48, 92, 89, 80, 27,  1, 21],
       [83, 59, 37,  9, 66, 79,  8, 93, 83, 43],
       [31, 38,  9,  3, 26, 34, 62, 29, 79, 98],
       [30, 75, 93, 28, 79, 75, 38,  4, 74, 82],
       [23, 48, 68, 64, 85, 24, 88, 14, 78, 85]])

In [45]:
matrix2[:4]

array([[55, 35,  1, 82, 46, 62, 38, 81, 76,  2],
       [ 1, 31, 98, 85, 48, 39, 41, 24,  5, 74],
       [83, 56, 22, 77, 83,  4, 33, 82, 91, 71],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14]])

In [47]:
matrix2[-1:4]

array([], shape=(0, 10), dtype=int32)

In [50]:
matrix2[-1,-4]

88

In [52]:
matrix2

array([[55, 35,  1, 82, 46, 62, 38, 81, 76,  2],
       [ 1, 31, 98, 85, 48, 39, 41, 24,  5, 74],
       [83, 56, 22, 77, 83,  4, 33, 82, 91, 71],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14],
       [42, 53, 82,  3, 73, 47, 50, 83, 11, 94],
       [89, 84, 96, 48, 92, 89, 80, 27,  1, 21],
       [83, 59, 37,  9, 66, 79,  8, 93, 83, 43],
       [31, 38,  9,  3, 26, 34, 62, 29, 79, 98],
       [30, 75, 93, 28, 79, 75, 38,  4, 74, 82],
       [23, 48, 68, 64, 85, 24, 88, 14, 78, 85]])

In [51]:
matrix2[::-1]

array([[23, 48, 68, 64, 85, 24, 88, 14, 78, 85],
       [30, 75, 93, 28, 79, 75, 38,  4, 74, 82],
       [31, 38,  9,  3, 26, 34, 62, 29, 79, 98],
       [83, 59, 37,  9, 66, 79,  8, 93, 83, 43],
       [89, 84, 96, 48, 92, 89, 80, 27,  1, 21],
       [42, 53, 82,  3, 73, 47, 50, 83, 11, 94],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14],
       [83, 56, 22, 77, 83,  4, 33, 82, 91, 71],
       [ 1, 31, 98, 85, 48, 39, 41, 24,  5, 74],
       [55, 35,  1, 82, 46, 62, 38, 81, 76,  2]])

In [59]:
matrix2[::-2]

array([[23, 48, 68, 64, 85, 24, 88, 14, 78, 85],
       [31, 38,  9,  3, 26, 34, 62, 29, 79, 98],
       [89, 84, 96, 48, 92, 89, 80, 27,  1, 21],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14],
       [ 1, 31, 98, 85, 48, 39, 41, 24,  5, 74]])

In [56]:
matrix2[::-3]

array([[23, 48, 68, 64, 85, 24, 88, 14, 78, 85],
       [83, 59, 37,  9, 66, 79,  8, 93, 83, 43],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14],
       [55, 35,  1, 82, 46, 62, 38, 81, 76,  2]])

In [58]:
matrix2

array([[55, 35,  1, 82, 46, 62, 38, 81, 76,  2],
       [ 1, 31, 98, 85, 48, 39, 41, 24,  5, 74],
       [83, 56, 22, 77, 83,  4, 33, 82, 91, 71],
       [42, 28, 44, 60, 14, 37, 65, 43, 30, 14],
       [42, 53, 82,  3, 73, 47, 50, 83, 11, 94],
       [89, 84, 96, 48, 92, 89, 80, 27,  1, 21],
       [83, 59, 37,  9, 66, 79,  8, 93, 83, 43],
       [31, 38,  9,  3, 26, 34, 62, 29, 79, 98],
       [30, 75, 93, 28, 79, 75, 38,  4, 74, 82],
       [23, 48, 68, 64, 85, 24, 88, 14, 78, 85]])

In [57]:
matrix2[::-5]

array([[23, 48, 68, 64, 85, 24, 88, 14, 78, 85],
       [42, 53, 82,  3, 73, 47, 50, 83, 11, 94]])

In [60]:
matrix2.max()

98

In [61]:
matrix2.min()

1

In [62]:
matrix2.mean()

51.92

In [63]:
from numpy import *
median(matrix2)

49.0

In [64]:
mean(matrix2)

51.92

In [72]:
output = np.arange(0,500)
output.reshape(50,10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [73]:
output.reshape(50,10,order='C')

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [74]:
output.reshape(50,10,order='F')

array([[  0,  50, 100, 150, 200, 250, 300, 350, 400, 450],
       [  1,  51, 101, 151, 201, 251, 301, 351, 401, 451],
       [  2,  52, 102, 152, 202, 252, 302, 352, 402, 452],
       [  3,  53, 103, 153, 203, 253, 303, 353, 403, 453],
       [  4,  54, 104, 154, 204, 254, 304, 354, 404, 454],
       [  5,  55, 105, 155, 205, 255, 305, 355, 405, 455],
       [  6,  56, 106, 156, 206, 256, 306, 356, 406, 456],
       [  7,  57, 107, 157, 207, 257, 307, 357, 407, 457],
       [  8,  58, 108, 158, 208, 258, 308, 358, 408, 458],
       [  9,  59, 109, 159, 209, 259, 309, 359, 409, 459],
       [ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460],
       [ 11,  61, 111, 161, 211, 261, 311, 361, 411, 461],
       [ 12,  62, 112, 162, 212, 262, 312, 362, 412, 462],
       [ 13,  63, 113, 163, 213, 263, 313, 363, 413, 463],
       [ 14,  64, 114, 164, 214, 264, 314, 364, 414, 464],
       [ 15,  65, 115, 165, 215, 265, 315, 365, 415, 465],
       [ 16,  66, 116, 166, 216, 266, 316, 366, 416, 466

In [80]:
output = output.reshape(50,10,order='F')
output

array([[  0,  50, 100, 150, 200, 250, 300, 350, 400, 450],
       [  1,  51, 101, 151, 201, 251, 301, 351, 401, 451],
       [  2,  52, 102, 152, 202, 252, 302, 352, 402, 452],
       [  3,  53, 103, 153, 203, 253, 303, 353, 403, 453],
       [  4,  54, 104, 154, 204, 254, 304, 354, 404, 454],
       [  5,  55, 105, 155, 205, 255, 305, 355, 405, 455],
       [  6,  56, 106, 156, 206, 256, 306, 356, 406, 456],
       [  7,  57, 107, 157, 207, 257, 307, 357, 407, 457],
       [  8,  58, 108, 158, 208, 258, 308, 358, 408, 458],
       [  9,  59, 109, 159, 209, 259, 309, 359, 409, 459],
       [ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460],
       [ 11,  61, 111, 161, 211, 261, 311, 361, 411, 461],
       [ 12,  62, 112, 162, 212, 262, 312, 362, 412, 462],
       [ 13,  63, 113, 163, 213, 263, 313, 363, 413, 463],
       [ 14,  64, 114, 164, 214, 264, 314, 364, 414, 464],
       [ 15,  65, 115, 165, 215, 265, 315, 365, 415, 465],
       [ 16,  66, 116, 166, 216, 266, 316, 366, 416, 466

In [81]:
output.reshape(50,10,order='A')
output

array([[  0,  50, 100, 150, 200, 250, 300, 350, 400, 450],
       [  1,  51, 101, 151, 201, 251, 301, 351, 401, 451],
       [  2,  52, 102, 152, 202, 252, 302, 352, 402, 452],
       [  3,  53, 103, 153, 203, 253, 303, 353, 403, 453],
       [  4,  54, 104, 154, 204, 254, 304, 354, 404, 454],
       [  5,  55, 105, 155, 205, 255, 305, 355, 405, 455],
       [  6,  56, 106, 156, 206, 256, 306, 356, 406, 456],
       [  7,  57, 107, 157, 207, 257, 307, 357, 407, 457],
       [  8,  58, 108, 158, 208, 258, 308, 358, 408, 458],
       [  9,  59, 109, 159, 209, 259, 309, 359, 409, 459],
       [ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460],
       [ 11,  61, 111, 161, 211, 261, 311, 361, 411, 461],
       [ 12,  62, 112, 162, 212, 262, 312, 362, 412, 462],
       [ 13,  63, 113, 163, 213, 263, 313, 363, 413, 463],
       [ 14,  64, 114, 164, 214, 264, 314, 364, 414, 464],
       [ 15,  65, 115, 165, 215, 265, 315, 365, 415, 465],
       [ 16,  66, 116, 166, 216, 266, 316, 366, 416, 466

In [109]:
array1 = np.arange(0,30)
array1.reshape(6,5,order='C')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [111]:
array1.reshape(6,5,order='A')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [112]:
array2 = np.arange(0,30)
array2.reshape(6,5,order='F')

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [115]:
array2.reshape(6,5,order='A')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [117]:
matrix = np.arange(0,100).reshape(10,10) 

In [118]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
matrix[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [120]:
matrix[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [121]:
matrix[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [123]:
matrix[:,:6]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [60, 61, 62, 63, 64, 65],
       [70, 71, 72, 73, 74, 75],
       [80, 81, 82, 83, 84, 85],
       [90, 91, 92, 93, 94, 95]])

In [124]:
matrix[:,6:]

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19],
       [26, 27, 28, 29],
       [36, 37, 38, 39],
       [46, 47, 48, 49],
       [56, 57, 58, 59],
       [66, 67, 68, 69],
       [76, 77, 78, 79],
       [86, 87, 88, 89],
       [96, 97, 98, 99]])

In [125]:
matrix[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [126]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [127]:
matrix[6,:]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [128]:
matrix[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [129]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
matrix[3,-3]

37

In [133]:
matrix[3:5,-3]

array([37, 47])

In [134]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
matrix[10:0]

array([], shape=(0, 10), dtype=int32)

In [138]:
matrix[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
matrix[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [140]:
matrix[matrix<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [141]:
matrix[matrix<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [142]:
matrix[matrix>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [143]:
matrix[matrix!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])